name: Tests

on:
  push:
  pull_request:
    branches: [master]

jobs:
  test:
    name: ${{ matrix.redis-version }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        redis-version:
          - "redis:5"
          - "redis:6"
          - "redis:7.0"
          - "redis:7.2"
          - "redis:7.4"
          - "valkey/valkey:7.2"
          - "valkey/valkey:8"

    services:
      redis:
        image: ${{ matrix.redis-version }}
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Build everything
        run: make clean all

      - name: Ensure latest built version are in the repo
        run: git diff --exit-code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: make test
