name: Tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: redis ${{ matrix.redis-version }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        redis-version: [6, 7, '7.2', '7.4']

    services:
      redis:
        image: redis:${{ matrix.redis-version }}
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: LizardByte/setup-python-action@master
      with:
        python-version: '2.7'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: make test